### ISSUE TITLE
How to use this library with Angular ?

### ISSUE THREAD

**Issue by nblavoie** [jesstelford/node-MarkerWithLabel#17]
Trying to use this library with Angular 5 and I'm getting the following error : 

`TypeError: Cannot read property 'prototype' of undefined`

Here is what I'm doing :

`import MarkerWithLabel from 'markerwithlabel';`

`        const marker = new MarkerWithLabel({
          position: new google.maps.LatLng(
            geoPoint.position.latitude,
            geoPoint.position.longitude
          ),
          map: this.map,
          draggable: true,
          raiseOnDrag: true,
          labelContent: 'A',
          labelAnchor: new google.maps.Point(3, 30),
          labelClass: 'labels', // the CSS class for the label
          labelInBackground: false
        });
`

**Comment by vijaycreatise** [comment]
@nblavoie Did u get solution to this. I'm facing same problem. Can you please guide me on this if you have got solution.
