### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by cjuneja** [jesstelford/node-MarkerWithLabel#9]
ERROR in ./~/markerwithlabel/index.js
Module build failed: SyntaxError: Unexpected token (50:0)

There is an extra } on line 50 in index.js with latest update this morning.

**Comment by jesstelford** [comment]
Thanks for reporting the bug!

It should be fixed in `markerwithlabel@1.1.15` 👍

**Comment by cjuneja** [comment]
Thanks @jesstelford , I have also noticed that the numbers on google maps pushpins are also broken with the latest release.
![google-maps](https://cloud.githubusercontent.com/assets/4822048/15487587/802a6070-2103-11e6-935f-235b3a8c8f89.JPG)
![google-maps_no_marker](https://cloud.githubusercontent.com/assets/4822048/15487707/406697fa-2104-11e6-8cea-4dcb550a4f2d.JPG)

**Comment by jesstelford** [comment]
Hmm. I didn't see that. Can you share a small reproducible codebase?

**Comment by jesstelford** [comment]
Oh, I see it now. I'm working on a fix :)

**Comment by jesstelford** [comment]
I've rolled back the changes. If you get `v1.1.16` now, the original behaviour will be reinstated.

I'll be releasing a `v2.0.0` soon which should support the new usecase the original (buggy) merge was meant to fix.

**Comment by cjuneja** [comment]
Thank you @jesstelford. appreciate your quick response.

**Comment by jesstelford** [comment]
I've published a new version which enforces explicitly passing in the `google.maps` object, so it meets the need of #7, and also maintains correct existing behaviour: `markerwithlabel@2.0.0`
